### ISSUE TITLE
About model weight

### ISSUE THREAD

**Issue by VitaLemonTea1** [jzhzhang/NaVid-VLN-CE#2]
Hi,
Great work and thanks for releasing eval code.  After installing the environment and organizing the dataset , when starting the evaluation, I receive a message indicating that many weights are not being used. Is this normal?

**Comment by jzhzhang** [comment]
These warnings are caused by the initialization of the post. We only use a part of the weight of EVA-CLIP. These warnings do not affect the evaluation.

**Comment by VitaLemonTea1** [comment]
Thanks!
